// Code generated by goctl. DO NOT EDIT.
package types

type SignUpReq struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Age       int    `json:"age"`
}

type MessageRes struct {
	Message string `json:"message"`
}

type SignInReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignInRes struct {
	Token string `json:"token"`
}

type GetProfileRes struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Age       int    `json:"age"`
}

type UpdateProfileReq struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Age       int    `json:"age"`
}

type CreateArticleReq struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type GetArticleReq struct {
	ArticleId int `path:"article_id"`
}

type GetArticleRes struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type UpdateArticleReq struct {
	Id    int    `path:"article_id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

type DeleteArticleReq struct {
	Id int `path:"article_id"`
}
